moved conf files around, updated pxf script

diff --git a/server/pxf-service/src/scripts/pxf-service b/server/pxf-service/src/scripts/pxf-service
--- a/server/pxf-service/src/scripts/pxf-service
+++ b/server/pxf-service/src/scripts/pxf-service
@@ -20,42 +20,42 @@
 # pxf-service	start/stop/initialize/status the PXF instance
 #
 
+# establish PXF_HOME
 if [ -z ${PXF_HOME} ]; then
-    parent_script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
-    env_script=${parent_script_dir}/conf/pxf-env.sh
-else
-    env_script=${PXF_HOME}/conf/pxf-env.sh
+    export PXF_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 fi
-
-# load pxf-env.sh script
-if [ ! -f ${env_script} ]; then
-	echo WARNING: failed to find $env_script
-else
-	source ${env_script}
-fi
-
-pxf_user=${PXF_USER}
-instance_port=${PXF_PORT:-5888}
-instance_name=pxf-service
-pxf_debug=${PXF_DEBUG:-false}
-
-if [ -z ${PXF_HOME} ]; then
-    # RPM based setup
-    pxf_root=/usr/lib/pxf
-    tomcat_root=/opt/apache-tomcat
-    tomcat_templates=/opt/pxf/tomcat-templates
-    instance_root=/var/pxf
-    instance_owner=$pxf_user:$pxf_user
-else
-    # OSS/Source code based setup
-    pxf_root=${PXF_HOME}/lib
-    tomcat_root=${PXF_HOME}/apache-tomcat
-    tomcat_templates=${PXF_HOME}/tomcat-templates
-    instance_root=${PXF_HOME}
-    instance_owner=${pxf_user}
-fi
+default_env_script=${PXF_HOME}/conf/pxf-env-default.sh
 
 curl=`which curl`
+
+function update_pxf_conf()
+{
+    if [ "${PXF_CONF}" == "" ] && [ "${MASTER_DATA_DIRECTORY}" = "" ]; then
+        fail "neither PXF_CONF nor MASTER_DATA_DIRECTORY variables are set"
+    fi
+    export PXF_CONF=${PXF_CONF:=${MASTER_DATA_DIRECTORY}/pxf}
+    sed -i -e "s|{PXF_CONF:=.*}$|{PXF_CONF:=\"${PXF_CONF}\"}|g" ${default_env_script}
+}
+
+function get_environment()
+{
+    local init_mode=$1
+
+
+
+    # load default environment
+    if [ ! -f ${default_env_script} ]; then
+	    echo "ERROR: failed to find ${default_env_script}"
+	    exit 1
+    fi
+    source ${default_env_script}
+
+
+    tomcat_root=${PXF_HOME}/apache-tomcat
+    tomcat_templates=${PXF_HOME}/templates/tomcat
+    instance_root=${PXF_HOME}
+    instance_name=pxf-service
+}
 
 # print error message and return with error code
 function fail()
@@ -79,8 +79,8 @@ function createInstance()
 		return 1
 	fi
 
-    if [ ! -z ${pxf_user} ]; then
-        chown -R ${instance_owner} ${instance_root}
+    if [ ! -z ${PXF_USER} ]; then
+        chown -R ${PXF_USER} ${instance_root}
     fi
     chmod 700 ${instance_root}/${instance_name}
 
@@ -98,8 +98,8 @@ function createInstance()
 #
 function deployWebapp()
 {
-	cp ${pxf_root}/pxf.war ${instance_root}/${instance_name}/webapps/ || return 1
-	cp ${pxf_root}/pxf-service-*[0-9].jar ${instance_root}/${instance_name}/lib/ || return 1
+	cp ${PXF_HOME}/lib/pxf.war ${instance_root}/${instance_name}/webapps/ || return 1
+	cp ${PXF_HOME}/lib/pxf-service-*[0-9].jar ${instance_root}/${instance_name}/lib/ || return 1
 
 	return 0
 }
@@ -116,7 +116,7 @@ function waitForTomcat()
 
 	# wait until tomcat is up:
 	echo Checking if tomcat is up and running...
-	until [[ "`curl --silent --connect-timeout 1 -I http://localhost:${instance_port} | grep 'Coyote'`" != "" ]];
+	until [[ "`curl --silent --connect-timeout 1 -I http://localhost:${PXF_PORT} | grep 'Coyote'`" != "" ]];
 	do
 		let attempts=attempts+1
 		if [[ "$attempts" -eq "$max_attempts" ]]; then
@@ -139,11 +139,11 @@ function checkWebapp()
 	waitForTomcat $1 || return 1
 
 	echo Checking if PXF webapp is up and running...
-	curlResponse=$(${curl} -s "http://localhost:${instance_port}/pxf/v0")
+	curlResponse=$(${curl} -s "http://localhost:${PXF_PORT}/pxf/v0")
 	expectedResponse="Wrong version v0, supported version is v[0-9]+"
 
 	if [[ ${curlResponse} =~ $expectedResponse ]]; then
-		echo PXF webapp is listening on port ${instance_port}
+		echo PXF webapp is listening on port ${PXF_PORT}
 		return 0
 	fi
 
@@ -171,7 +171,9 @@ function doInit()
 		echo WARNING: instance already exists in ${instance_root}, nothing to do...
 		return 0
 	fi
+
 	generatePrivateClasspath || return 1
+	generateUserConfigs || return 1
 	createInstance || return 1
 	deployWebapp || return 1
 	createLogsDir || return 1
@@ -204,7 +206,7 @@ function configureWebapp()
 
     # set port
     catalinaProperties=${instance_root}/${instance_name}/conf/catalina.properties
-    sed -i -e "s|^[[:blank:]]*connector.http.port=.*$|connector.http.port=$instance_port|g" ${catalinaProperties}
+    sed -i -e "s|^[[:blank:]]*connector.http.port=.*$|connector.http.port=${PXF_PORT}|g" ${catalinaProperties}
 
     # set container configs
     catalinaEnv=${instance_root}/${instance_name}/bin/setenv.sh
@@ -224,13 +226,13 @@ function configureWebapp()
 function commandWebapp()
 {
     command=$1
-    if [ "${pxf_debug}" == "true" ] && [ "${command}" == "start" ]; then
+    if [ "${PXF_DEBUG}" == "true" ] && [ "${command}" == "start" ]; then
         command="jpda $command"
     fi
     pushd ${instance_root} > /dev/null
-    if [ ! -z ${pxf_user} ]; then
-        # Run command as a pxf_user
-        su ${pxf_user} -c "$instance_root/$instance_name/bin/catalina.sh $command"
+    if [ ! -z ${PXF_USER} ]; then
+        # Run command as a PXF_USER
+        su ${PXF_USER} -c "$instance_root/$instance_name/bin/catalina.sh $command"
     else
         # Run command as a current user
         ${instance_root}/${instance_name}/bin/catalina.sh ${command}
@@ -243,37 +245,70 @@ function commandWebapp()
 
 function createLogsDir()
 {
-    mkdir -p ${PXF_LOGDIR}
-    if [ ! -z ${pxf_user} ]; then
-        chown -R ${instance_owner} ${PXF_LOGDIR}
+    # logs dir is likely outside PXF_HOME, setup only if it does not yet exist
+    if [ ! -d "${PXF_LOGDIR}" ]; then
+        mkdir -p ${PXF_LOGDIR}
+        if [ ! -z ${PXF_USER} ]; then
+            chown -R ${PXF_USER} ${PXF_LOGDIR}
+        fi
+        chmod 700 ${PXF_LOGDIR}
     fi
-    chmod 700 ${PXF_LOGDIR}
-    return 0
 }
 
 function createRunDir()
 {
     mkdir -p ${PXF_RUNDIR}
-    if [ ! -z ${pxf_user} ]; then
-        chown -R ${instance_owner} ${PXF_RUNDIR}
+    if [ ! -z ${PXF_USER} ]; then
+        chown -R ${PXF_USER} ${PXF_RUNDIR}
     fi
     chmod 700 ${PXF_RUNDIR}
-    return 0
 }
 
 function generatePrivateClasspath()
 {
     # verify that a template file for the distribution exists
-    local template_file="${PXF_HOME}/conf-templates/pxf-private.classpath.template"
+    local template_file="${PXF_HOME}/templates/pxf/pxf-private.classpath.template"
     if [ ! -f "${template_file}" ]; then
         fail "Template file ${template_file} not found"
     fi
 
     echo "Generating ${PXF_HOME}/conf/pxf-private.classpath file from ${template_file} ..."
 
-    # create initial version of the file by replacing PXF_HOME token (applicable to all templates)
-    sed -e "s|PXF_HOME|${PXF_HOME}|g" ${template_file} > ${PXF_HOME}/conf/pxf-private.classpath
+    # create initial version of the file by replacing PXF_HOME and PXF_CONF tokens
+    cp ${template_file} ${PXF_HOME}/conf/pxf-private.classpath
+    sed -i -e "s|PXF_HOME|${PXF_HOME}|g" ${PXF_HOME}/conf/pxf-private.classpath
+    sed -i -e "s|PXF_CONF|${PXF_CONF}|g" ${PXF_HOME}/conf/pxf-private.classpath
+}
 
+function generateUserConfigs()
+{
+    # create and setup user configuration directories (only if they do not exist)
+    setup_conf_directory ${PXF_CONF}
+    setup_conf_directory ${PXF_CONF}/conf ${PXF_HOME}/templates/user/conf
+    setup_conf_directory ${PXF_CONF}/logs
+    setup_conf_directory ${PXF_CONF}/servers ${PXF_HOME}/templates/user/servers
+}
+
+function setup_conf_directory()
+{
+    local target=$1
+    local source=$2
+
+    if [ ! -d "${target}" ]; then
+        if [ "x${source}" == "x" ]; then
+            echo "Creating directory ${target}"
+            mkdir -p ${target}
+        else
+            echo "Copying configurations from ${source} to ${target}"
+            cp -R ${source} $( dirname ${target} )
+        fi
+        if [ ! -z ${PXF_USER} ]; then
+            echo "Updating ownership of ${target} to ${PXF_USER}"
+            chown -R ${PXF_USER} ${target}
+        fi
+    else
+        echo "Directory ${target} already exists, no update required"
+    fi
 }
 
 function printUsage()
@@ -301,11 +336,11 @@ function validateParameters()
     fi
 
     # validate pxf user
-    if [ ! -z ${pxf_user} ]; then
-        id ${pxf_user}  &> /dev/null;
+    if [ ! -z ${PXF_USER} ]; then
+        id ${PXF_USER}  &> /dev/null;
         if [ "$?" -ne "0" ]
         then
-            echo "ERROR: User $pxf_user doesn't exist. Please set valid user via \$PXF_USER variable"
+            echo "ERROR: User ${PXF_USER} doesn't exist. Please set valid user via PXF_USER variable"
             exit 1
         fi
     fi
@@ -327,7 +362,7 @@ function validateParameters()
 
 #
 # doStart handles start command
-# command is executed as the user $pxf_user
+# command is executed as the user $PXF_USER
 #
 # after start, uses checkWebapp to verify the PXF webapp was loaded
 # successfully
@@ -346,7 +381,7 @@ function doStart()
 
 #
 # doStart handles stop command
-# command is executed as the user $pxf_user
+# command is executed as the user $PXF_USER
 #
 #
 function doStop()
@@ -368,24 +403,30 @@ command=$1
 
 case "$command" in
 	"init" )
+		update_pxf_conf
+		get_environment init
 		validateParameters
 		doInit
 		;;
 	"start" )
+		get_environment
 		validateParameters
 		doStart
 		;;
 	"stop" )
+		get_environment
 		validateParameters
 		doStop
 		;;
 	"restart" )
+		get_environment
 		validateParameters
 		doStop
 		sleep 1s
 		doStart
 		;;
 	"status" )
+		get_environment
 		validateParameters
 		doStatus
 		;;
