Add tests for error cases of update-config CLI
Co-authored-by: Divya Bhargov <dbhargov@pivotal.io>
Co-authored-by: Ben Christel <bchristel@pivotal.io>

diff --git a/server/pxf-service/src/scripts/pxf-service b/server/pxf-service/src/scripts/pxf-service
--- a/server/pxf-service/src/scripts/pxf-service
+++ b/server/pxf-service/src/scripts/pxf-service
@@ -410,12 +410,68 @@ function doStatus()
 	checkWebapp 1 || return 1
 }
 
+function printUpdateConfigUsage()
+{
+    >&2 echo "Usage: pxf update-config -f hostfile.txt"
+}
+
+function doUpdateConfig()
+{
+    local hostfile
+    local config_dir="$PXF_USER_HOME/conf"
+    export PXF_USER_HOME=/home/gpadmin/foobar/pxf # TODO: remove this
+
+    shift # don't try to parse the update-config arg
+    if [ "$#" -eq 0 ]; then
+        >&2 echo 'update-config requires arguments'
+        printUpdateConfigUsage
+        return 1
+    fi
+
+    while getopts ':f:' opt; do
+        case "${opt}" in
+            f )
+                hostfile="$2"
+                ;;
+            \? )
+                >&2 echo "Unrecognized option: -$OPTARG"
+                printUpdateConfigUsage
+                return 1
+                ;;
+            : )
+                >&2 echo "Invalid option: -$OPTARG requires an argument"
+                printUpdateConfigUsage
+                return 1
+                ;;
+        esac
+    done
+
+    if [ "$#" -ne 0 ]; then
+        >&2 echo "Unrecognized arguments: $@"
+    fi
+
+    if [ -z "$hostfile" ]; then
+        >&2 echo "Invalid option: -f requires an argument"
+        return 1
+    fi
+
+    if [ ! -e "$hostfile" ]; then
+        >&2 echo "Invalid option: $hostfile is not a file"
+        return 1
+    fi
+
+    gpssh -f "$hostfile" mktemp -d ''
+    gpscp -r "$PXF_USER_HOME/conf" gpadmin@=:"$PXF_USER_HOME/conf" -f "$hostfile"
+}
+
 pxf_script_command=$1
 
 silent=false
 if [ "$2" == "-y" ] || [ "$2" == "-Y" ]; then
 	silent=true
 fi
+
+command=$1
 
 validate_user
 validate_system
@@ -438,6 +494,9 @@ case "${pxf_script_command}" in
 	"status" )
 		doStatus
 		;;
+	"update-config" )
+	    doUpdateConfig "$@"
+	    ;;
 	* )
 		printUsage
 		exit 2
